import { syntheticApplicant } from "@/lib/case/seed";
import type { ApplicantCase, PostalAddress } from "@/lib/case/types";
import { canonicalValue as cv } from "@/lib/case/value";

export function createEmptyApplicantCase(): ApplicantCase {
  return {
    ...structuredClone(syntheticApplicant),
    caseId: "current-session",
    mode: "session",
    stage: "application",
    conversationLocale: null,
    applicationPhase: "language",
    activeQuestionId: null,
    deferredItems: [],
    documentReadiness: {},
    collectionCompletion: {
      providers: "unanswered",
      medications: "unanswered",
      jobs: "unanswered",
      marriages: "unanswered",
      children: "unanswered",
    },
    finalReviewApproved: false,
    applicant: {
      legalName: cv<string>(null, "missing", "typed"),
      otherNames: cv<string[]>([], "confirmed", "typed"),
      ssn: cv<string>(null, "missing", "typed"),
      dateOfBirth: cv<string>(null, "missing", "typed"),
      placeOfBirth: cv<string>(null, "missing", "typed"),
      citizenship: cv<string>(null, "missing", "typed"),
      preferredLanguage: cv<string>(null, "missing", "typed"),
      address: cv<PostalAddress>(null, "missing", "typed"),
      phone: cv<string>(null, "missing", "typed"),
      email: cv<string>(null, "missing", "typed"),
    },
    eligibilityInput: {
      monthlyEarningsUsd: null,
      statutorilyBlind: null,
      impairmentRelatedWorkExpensesUsd: null,
      employerSubsidyPossible: null,
      selfEmployed: null,
      selfEmploymentProfitUsd: null,
      passiveIncomeIncluded: null,
      conditionExpectedToLast12Months: null,
      conditionExpectedToResultInDeath: null,
      dateOfBirth: null,
      allegedOnsetDate: null,
      estimatedLifetimeCredits: null,
      creditsLast3Years: null,
      creditsLast10Years: null,
      workedYearsAfter21BeforeOnset: null,
    },
    conditions: [],
    providers: [],
    medications: [],
    jobs: [],
    marriages: [],
    children: [],
    claimContacts: [],
    medicalTests: [],
    education: {
      highestLevel: cv<string>(null, "missing", "typed"),
      completionDate: cv<string>(null, "missing", "typed"),
      schoolName: cv<string>(null, "missing", "typed"),
      schoolAddress: cv<PostalAddress>(null, "missing", "typed"),
      specialEducation: cv<boolean>(null, "missing", "typed"),
      specialEducationDetails: cv<string>(null, "missing", "typed"),
      training: cv<string[]>(null, "missing", "typed"),
      trainingFacility: cv<string>(null, "missing", "typed"),
      trainingFacilityPhone: cv<string>(null, "missing", "typed"),
      trainingFacilityAddress: cv<PostalAddress>(null, "missing", "typed"),
      writtenLanguage: cv("English", "confirmed", "typed"),
    },
    servedInMilitary: cv<boolean>(null, "missing", "typed"),
    nonCitizen: cv<boolean>(null, "missing", "typed"),
    workedLastYear: cv<boolean>(null, "missing", "typed"),
    currentlyEarning: cv<boolean>(null, "missing", "typed"),
    bankDetailsReady: cv<boolean>(null, "missing", "typed"),
    otherPublicDisabilityBenefitsFiled: cv<boolean>(
      null,
      "missing",
      "typed",
    ),
    otherPublicDisabilityBenefitTypes: cv<string[]>(
      [],
      "confirmed",
      "typed",
    ),
    bankRoutingNumber: cv<string>(null, "missing", "typed"),
    bankAccountNumber: cv<string>(null, "missing", "typed"),
    bankAccountType: cv<string>(null, "missing", "typed"),
    directDepositRefused: cv<boolean>(null, "missing", "typed"),
    interviewTurns: [],
    providerCollectionComplete: false,
    recordRequests: [],
    authorization: {
      signedAt: null,
      additionalBlankOriginalRequested: false,
    },
    documentState: {
      generatedRevision: null,
      status: "not_started",
    },
    revision: 0,
  };
}
