import type { ApplicantCase } from "@/lib/case/types";
import { canonicalValue as cv } from "@/lib/case/value";

const address = {
  line1: "REDACTED",
  city: "Sacramento",
  state: "CA",
  zip: "95814",
};

export const syntheticApplicant: ApplicantCase = {
  caseId: "demo-elena-rivera",
  mode: "synthetic_demo",
  stage: "application",
  conversationLocale: "en-US",
  applicationPhase: "ready",
  activeQuestionId: null,
  deferredItems: [],
  documentReadiness: {
    "birth-certificate": "ready",
    ssn: "ready",
    "photo-id": "ready",
    banking: "ready",
  },
  collectionCompletion: {
    providers: "complete_with_items",
    medications: "complete_with_items",
    jobs: "complete_with_items",
    marriages: "complete_none",
    children: "complete_none",
  },
  finalReviewApproved: true,
  applicant: {
    legalName: cv("Elena Rivera", "confirmed"),
    otherNames: cv([], "confirmed"),
    ssn: cv("REDACTED", "confirmed"),
    dateOfBirth: cv("1978-04-12", "confirmed"),
    placeOfBirth: cv("Sacramento, California", "confirmed"),
    citizenship: cv("United States", "confirmed"),
    preferredLanguage: cv("English", "confirmed"),
    address: cv(address, "confirmed"),
    phone: cv("(916) 555-0147", "confirmed"),
    email: cv("REDACTED", "confirmed"),
  },
  eligibilityInput: {
    monthlyEarningsUsd: 1480,
    statutorilyBlind: false,
    impairmentRelatedWorkExpensesUsd: 180,
    employerSubsidyPossible: true,
    selfEmployed: false,
    selfEmploymentProfitUsd: null,
    passiveIncomeIncluded: false,
    conditionExpectedToLast12Months: true,
    conditionExpectedToResultInDeath: false,
    dateOfBirth: "1978-04-12",
    allegedOnsetDate: "2025-10-18",
    estimatedLifetimeCredits: 31,
    creditsLast3Years: 8,
    creditsLast10Years: 18,
    workedYearsAfter21BeforeOnset: 21,
  },
  conditions: [
    {
      id: "condition-lumbar",
      name: cv("Lumbar spinal stenosis", "confirmed"),
      allegedOnsetDate: cv("2025-10-18", "confirmed"),
      symptoms: cv(
        ["lower-back pain", "leg numbness", "limited standing"],
        "confirmed",
      ),
      workEffects: cv(
        [
          "cannot stand longer than 15 minutes",
          "needs frequent position changes",
        ],
        "confirmed",
      ),
    },
    {
      id: "condition-migraine",
      name: cv("Chronic migraine", "confirmed"),
      allegedOnsetDate: cv("2024-06-01", "confirmed"),
      symptoms: cv(
        ["light sensitivity", "nausea", "difficulty concentrating"],
        "confirmed",
      ),
      workEffects: cv(
        ["misses work two to three days each month"],
        "confirmed",
      ),
    },
  ],
  providers: [
    {
      id: "provider-chen",
      name: cv("Dr. Maya Chen", "confirmed"),
      facility: cv("Sacramento Spine & Rehab", "confirmed"),
      specialty: cv("Physical medicine and rehabilitation", "confirmed"),
      address: cv(
        {
          line1: "620 Q Street",
          city: "Sacramento",
          state: "CA",
          zip: "95811",
        },
        "confirmed",
      ),
      phone: cv("(916) 555-0123", "confirmed"),
      firstTreatmentDate: cv("2024-11-14", "confirmed"),
      lastTreatmentDate: cv("2026-06-30", "confirmed"),
      nextAppointmentDate: cv("2026-08-04", "confirmed"),
      conditionIds: ["condition-lumbar"],
    },
    {
      id: "provider-owens",
      name: cv("Dr. Simon Owens", "confirmed"),
      facility: cv("River City Neurology", "confirmed"),
      specialty: cv("Neurology", "confirmed"),
      address: cv(
        {
          line1: "912 Capitol Mall",
          city: "Sacramento",
          state: "CA",
          zip: "95814",
        },
        "confirmed",
      ),
      phone: cv("(916) 555-0191", "confirmed"),
      firstTreatmentDate: cv("2025-02-02", "confirmed"),
      lastTreatmentDate: cv("2026-05-22", "confirmed"),
      nextAppointmentDate: cv<string>(null, "missing"),
      conditionIds: ["condition-migraine"],
    },
    {
      id: "provider-mercy",
      name: cv("Mercy General Hospital", "confirmed"),
      facility: cv("Mercy General Hospital", "confirmed"),
      specialty: cv("Emergency department", "confirmed"),
      address: cv(
        {
          line1: "4001 J Street",
          city: "Sacramento",
          state: "CA",
          zip: "95819",
        },
        "confirmed",
      ),
      phone: cv("(916) 555-0188", "confirmed"),
      firstTreatmentDate: cv("2025-10-18", "confirmed"),
      lastTreatmentDate: cv("2025-10-18", "confirmed"),
      nextAppointmentDate: cv<string>(null, "not_applicable"),
      conditionIds: ["condition-lumbar"],
    },
  ],
  medications: [
    {
      id: "med-gabapentin",
      name: cv("Gabapentin", "confirmed"),
      dosage: cv("300 mg", "confirmed"),
      frequency: cv("three times daily", "confirmed"),
      prescriberProviderId: cv("provider-chen", "confirmed"),
      reason: cv("nerve pain", "confirmed"),
      sideEffects: cv(["drowsiness"], "confirmed"),
    },
    {
      id: "med-sumatriptan",
      name: cv("Sumatriptan", "confirmed"),
      dosage: cv("50 mg", "confirmed"),
      frequency: cv("as needed", "confirmed"),
      prescriberProviderId: cv("provider-owens", "confirmed"),
      reason: cv("migraine attacks", "confirmed"),
      sideEffects: cv([], "confirmed"),
    },
  ],
  jobs: [
    {
      id: "job-grocery",
      employer: cv("Capitol Fresh Market", "confirmed"),
      title: cv("Bakery department lead", "confirmed"),
      startDate: cv("2017-03-01", "confirmed"),
      endDate: cv("2025-11-02", "confirmed"),
      hoursPerDay: cv(8, "confirmed"),
      daysPerWeek: cv(5, "confirmed"),
      pay: cv(23.5, "confirmed"),
      duties: cv(
        [
          "scheduled staff",
          "prepared baked goods",
          "stocked displays",
          "served customers",
        ],
        "confirmed",
      ),
      physicalDemands: cv(
        {
          lifting: "Frequently lifted 20 pounds; occasionally 50 pounds",
          standingHours: 6,
          walkingHours: 2,
          sittingHours: 0,
          climbing: "Occasional step ladder",
          stooping: "Frequent",
          handling: "Constant",
        },
        "confirmed",
      ),
      toolsAndMachines: cv(["commercial mixer", "oven", "slicer"], "confirmed"),
      supervision: cv("Supervised four employees", "confirmed"),
      writingAndReports: cv(
        "Completed inventory and shift reports",
        "confirmed",
      ),
      reasonEnded: cv("Could no longer stand through a shift", "confirmed"),
    },
    {
      id: "job-coop",
      employer: cv("Northgate Community Co-op", "confirmed"),
      title: cv("Inventory labeler", "confirmed"),
      startDate: cv("2026-01-12", "confirmed"),
      endDate: cv<string>(null, "not_applicable"),
      hoursPerDay: cv(4, "confirmed"),
      daysPerWeek: cv(5, "confirmed"),
      pay: cv(17.08, "confirmed"),
      duties: cv(
        [
          "printed inventory labels",
          "checked item numbers",
          "updated stock counts",
        ],
        "confirmed",
      ),
      physicalDemands: cv(
        {
          lifting: "No more than 5 pounds",
          standingHours: 0.5,
          walkingHours: 0.5,
          sittingHours: 3,
          climbing: "None",
          stooping: "None",
          handling: "Frequent",
        },
        "confirmed",
      ),
      toolsAndMachines: cv(
        ["computer", "barcode scanner", "label printer"],
        "confirmed",
      ),
      supervision: cv(
        "Supervisor checks work and allows unscheduled breaks",
        "confirmed",
      ),
      writingAndReports: cv("Updates electronic inventory counts", "confirmed"),
      reasonEnded: cv<string>(null, "not_applicable"),
    },
  ],
  marriages: [],
  children: [],
  claimContacts: [
    {
      id: "contact-sofia",
      name: cv("Sofia Rivera", "confirmed"),
      relationship: cv("Sister", "confirmed"),
      address: cv(address, "confirmed"),
      phone: cv("(916) 555-0162", "confirmed"),
      speaksEnglish: cv(true, "confirmed"),
      preferredLanguage: cv("English", "confirmed"),
    },
  ],
  medicalTests: [
    {
      id: "test-mri",
      type: cv("MRI/CT scan", "confirmed"),
      bodyPart: cv("Lumbar spine", "confirmed"),
      providerOrFacility: cv("Mercy General Hospital", "confirmed"),
      date: cv("2025-10-18", "confirmed"),
    },
  ],
  education: {
    highestLevel: cv("12", "confirmed"),
    completionDate: cv("1996-06", "confirmed"),
    schoolName: cv("Sacramento High School", "confirmed"),
    schoolAddress: cv(
      {
        line1: "REDACTED",
        city: "Sacramento",
        state: "CA",
        zip: "95817",
      },
      "confirmed",
    ),
    specialEducation: cv(false, "confirmed"),
    specialEducationDetails: cv<string>(null, "not_applicable"),
    training: cv(["food safety certification"], "confirmed"),
    trainingFacility: cv("Capitol Fresh Market", "confirmed"),
    trainingFacilityPhone: cv("(916) 555-0175", "confirmed"),
    trainingFacilityAddress: cv(address, "confirmed"),
    writtenLanguage: cv("English", "confirmed"),
  },
  servedInMilitary: cv(false, "confirmed"),
  nonCitizen: cv(false, "confirmed"),
  workedLastYear: cv(true, "confirmed"),
  currentlyEarning: cv(true, "confirmed"),
  bankDetailsReady: cv(true, "confirmed"),
  otherPublicDisabilityBenefitsFiled: cv(false, "confirmed"),
  otherPublicDisabilityBenefitTypes: cv([], "confirmed"),
  bankRoutingNumber: cv("121000248", "confirmed"),
  bankAccountNumber: cv("000123456789", "confirmed"),
  bankAccountType: cv("checking", "confirmed"),
  directDepositRefused: cv(false, "confirmed"),
  interviewTurns: [],
  providerCollectionComplete: true,
  recordRequests: [
    {
      id: "request-chen",
      providerId: "provider-chen",
      providerDisplayName: "Dr. Maya Chen",
      providerPhone: "(916) 555-0123",
      portalAvailable: true,
      requestedAt: "2026-07-01",
      extensionNoticeAt: null,
      respondedAt: "2026-07-12",
      status: "responded",
    },
    {
      id: "request-owens",
      providerId: "provider-owens",
      providerDisplayName: "Dr. Simon Owens",
      providerPhone: "(916) 555-0191",
      portalAvailable: false,
      requestedAt: "2026-07-06",
      extensionNoticeAt: null,
      respondedAt: null,
      status: "silent",
    },
    {
      id: "request-mercy",
      providerId: "provider-mercy",
      providerDisplayName: "Mercy General Hospital",
      providerPhone: "(916) 555-0188",
      portalAvailable: true,
      requestedAt: "2026-06-18",
      extensionNoticeAt: null,
      respondedAt: null,
      status: "silent",
    },
  ],
  authorization: {
    signedAt: "2025-08-20",
    additionalBlankOriginalRequested: false,
  },
  documentState: {
    generatedRevision: null,
    status: "ready",
  },
  revision: 1,
};
