import { z } from "zod";

export const factFieldSchema = z.enum([
  "applicant.legalName",
  "applicant.otherNames",
  "applicant.ssn",
  "applicant.dateOfBirth",
  "applicant.placeOfBirth",
  "applicant.citizenship",
  "applicant.preferredLanguage",
  "applicant.addressLine1",
  "applicant.addressLine2",
  "applicant.city",
  "applicant.state",
  "applicant.zip",
  "applicant.phone",
  "applicant.email",
  "education.highestLevel",
  "education.completionDate",
  "education.schoolName",
  "education.schoolAddressLine1",
  "education.schoolAddressLine2",
  "education.schoolCity",
  "education.schoolState",
  "education.schoolZip",
  "education.specialEducation",
  "education.specialEducationDetails",
  "education.training",
  "education.trainingFacility",
  "education.trainingFacilityPhone",
  "education.trainingAddressLine1",
  "education.trainingAddressLine2",
  "education.trainingCity",
  "education.trainingState",
  "education.trainingZip",
  "education.writtenLanguage",
  "servedInMilitary",
  "nonCitizen",
  "workedLastYear",
  "currentlyEarning",
  "bankDetailsReady",
  "otherPublicDisabilityBenefitsFiled",
  "otherPublicDisabilityBenefitTypes",
  "bankRoutingNumber",
  "bankAccountNumber",
  "bankAccountType",
  "directDepositRefused",
  "condition.name",
  "condition.allegedOnsetDate",
  "condition.symptom",
  "condition.workEffect",
  "provider.name",
  "provider.facility",
  "provider.specialty",
  "provider.addressLine1",
  "provider.addressLine2",
  "provider.city",
  "provider.state",
  "provider.zip",
  "provider.phone",
  "provider.firstTreatmentDate",
  "provider.lastTreatmentDate",
  "provider.nextAppointmentDate",
  "provider.conditionTreated",
  "medication.name",
  "medication.dosage",
  "medication.frequency",
  "medication.prescriber",
  "medication.reason",
  "medication.sideEffect",
  "job.employer",
  "job.title",
  "job.startDate",
  "job.endDate",
  "job.hoursPerDay",
  "job.daysPerWeek",
  "job.pay",
  "job.duty",
  "job.lifting",
  "job.standingHours",
  "job.walkingHours",
  "job.sittingHours",
  "job.climbing",
  "job.stooping",
  "job.handling",
  "job.toolOrMachine",
  "job.supervision",
  "job.writingAndReports",
  "job.reasonEnded",
  "marriage.spouseName",
  "marriage.startDate",
  "marriage.endDate",
  "marriage.endReason",
  "child.name",
  "child.dateOfBirth",
  "child.ssn",
  "claimContact.name",
  "claimContact.relationship",
  "claimContact.addressLine1",
  "claimContact.addressLine2",
  "claimContact.city",
  "claimContact.state",
  "claimContact.zip",
  "claimContact.phone",
  "claimContact.speaksEnglish",
  "claimContact.preferredLanguage",
  "medicalTest.type",
  "medicalTest.bodyPart",
  "medicalTest.providerOrFacility",
  "medicalTest.date",
]);

export const extractedFactSchema = z.object({
  kind: z.enum([
    "scalar",
    "condition",
    "provider",
    "medication",
    "job",
    "marriage",
    "child",
    "claimContact",
    "medicalTest",
  ]),
  entityKey: z.string(),
  field: factFieldSchema,
  value: z.string(),
  confidence: z.number().min(0).max(1),
  evidenceText: z.string(),
});

export const interviewExtractionSchema = z.object({
  summary: z.string(),
  confirmationText: z.string().optional(),
  acknowledgement: z.string().optional(),
  answerComplete: z.boolean().optional(),
  followUpQuestion: z.string(),
  providerListStatus: z.enum(["complete", "more_possible", "unknown"]),
  facts: z.array(extractedFactSchema),
});

export const conversationContextMessageSchema = z.object({
  role: z.enum(["assistant", "user"]),
  content: z.string().trim().min(1).max(2_000),
});

export const extractionRequestSchema = z.object({
  turnId: z.string().min(1).max(100),
  locale: z.enum(["en-US", "es-US", "zh-CN"]).default("en-US"),
  topic: z.string().trim().min(1).max(100).optional(),
  prompt: z.string().trim().min(1).max(1_000).optional(),
  transcript: z.string().trim().min(1).max(8_000),
  history: z.array(conversationContextMessageSchema).max(48).default([]),
});

export type ExtractedFact = z.infer<typeof extractedFactSchema>;
export type InterviewExtraction = z.infer<typeof interviewExtractionSchema>;
export type ExtractionRequest = z.infer<typeof extractionRequestSchema>;
